name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run lint

  test:
    name: Unit Test (Jest)
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm test -- --coverage

  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: npm ci && npm test -- --coverage
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  k6-smoke:
    name: k6 Smoke Test
    runs-on: ubuntu-latest
    needs: [sonar]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - name: Start server
        run: nohup npm start >/dev/null 2>&1 &
      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/ >/dev/null; then exit 0; fi
            sleep 2
          done
          echo "Server never came up" && exit 1
      - uses: grafana/setup-k6-action@v1
      - name: Run k6
        env:
          BASE_URL: http://localhost:3000
        run: k6 run loadtest/script.js
